Repository otimlabs/otim-protocol, pull requests merged in 2025-07, with the labels that each got.

#18 fix: flaky snapshots
  .gas-snapshot
  .github/workflows/test.yml
  test/OtimDelegate.t.sol
  test/actions/DeactivateInstruction.t.sol
  test/actions/Refuel.t.sol
  test/actions/RefuelERC20.t.sol
  test/actions/SweepDepositAccount.t.sol
  test/actions/SweepDepositAccountERC20.t.sol
  test/actions/SweepSkipCCTPDepositAccount.t.sol
  test/actions/Transfer.t.sol
  test/actions/TransferERC20.t.sol
  test/actions/UniswapV3ExactInputSingle.t.sol
  test/actions/fee-models/OtimFee.t.sol
  test/actions/schedules/Interval.t.sol
  test/context/Receiver.t.sol
  test/core/ActionManager.t.sol
  test/core/Gateway.t.sol
  test/core/InstructionStorage.t.sol
  test/gas-estimation/EstimateDeactivateInstructionGasConstant.sol
  test/gas-estimation/EstimateRefuelERC20GasConstant.t.sol
  test/gas-estimation/EstimateRefuelGasConstant.t.sol
  test/gas-estimation/EstimateSweepDepositAccountERC20GasConstant.t.sol
  test/gas-estimation/EstimateSweepDepositAccountGasConstant.t.sol
  test/gas-estimation/EstimateSweepSkipCCTPDepositAccountGasConstant.t.sol
  test/gas-estimation/EstimateTransferERC20GasConstant.t.sol
  test/gas-estimation/EstimateTransferGasConstant.t.sol
  test/gas-estimation/EstimateUniswapV3ExactInputGasConstant.t.sol
  test/infrastructure/FeeTokenRegistry.t.sol
  test/infrastructure/Treasury.t.sol
Labels: fix

#21 feat: action argument decoding scripts
  .gas-snapshot
  script/utils/argument-decoding/DecodeDeactivateInstruction.s.sol
  script/utils/argument-decoding/DecodeRefuel.s.sol
  script/utils/argument-decoding/DecodeRefuelERC20.s.sol
  script/utils/argument-decoding/DecodeSweepDepositAccount.s.sol
  script/utils/argument-decoding/DecodeSweepDepositAccountERC20.s.sol
  script/utils/argument-decoding/DecodeSweepSkipCCTPDepositAccount.s.sol
  script/utils/argument-decoding/DecodeTransfer.s.sol
  script/utils/argument-decoding/DecodeTransferERC20.s.sol
  script/utils/argument-decoding/DecodeUniswapV3ExactInput.s.sol
Labels: feature

#16 feat: label protocol images as latest if artifacts match offchain
  .gas-snapshot
  .github/scripts/directory-comparison.rs
  .github/workflows/artifacts.yml
  .github/workflows/docker.yml
Labels: feature

#28 chore: fix docker artifact workflow call permissions
  .gas-snapshot
  .github/workflows/docker.yml
Labels: operations
